# Generated by Django 5.0.6 on 2024-07-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='model_car',
        ),
    ]
