# Generated by Django 5.0.6 on 2024-07-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_rename_model_car_model_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model_car',
            new_name='model',
        ),
    ]
